### ISSUE TITLE
'app.sections' no longer valid code in C5?

### ISSUE THREAD

**Issue by MattAppleton** [putyourlightson/sprig-components#1]
### Which plugin (and version/edition, if appropriate) does this enhancement relate to?

Sprig 3.5.0 with Craft 5.4.6

### Which section of the documentation or concept needs improving and why?

Video #3 — building Search filters...
https://putyourlightson.com/sprig/videos#sprigboard

### Your suggestions for how to better explain this section or concept.

I think part of the code has been superseded / entry-fied in Craft 5? 

At least for me it works to  replace `app.sections`  with `app.entries`

I was struggling to get this line of code to work

` {% set allowedSections = allowedSectionHandles|map(handle => craft.app.sections.sectionByHandle(handle)) %}`

BUT — this works though!

`{% set allowedSections = allowedSectionHandles|map(handle => craft.app.entries.sectionByHandle(handle)) %}`

**Great videos by the way,I'm learning a lot :)**

**Comment by bencroker** [comment]
Yes, you're right, it has. Not sure I'll be able to update the video, though.

**Comment by MattAppleton** [comment]
good point! Probably some AI tool for that — but really all it needs is an area for notes where the video is posted, Ryan does that sometimes on CraftQuest I noticed...

thanks again for this tool, getting somewhere with my first real-world implementation for an architect's site...

**Comment by bencroker** [comment]
Good idea – I added a note under the video at https://putyourlightson.com/sprig/videos#3-building-search-filters
